export const data = {
  products: [
    {
      name: "Black TShirt Men/Woman",
      slug: "black-tshirt-men-woman",
      image: "https://m.media-amazon.com/images/I/714s29JGWIL._AC_UY500_.jpg",
      price: 12,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Tshit for men and women",
    },
    {
      name: "Gildan Men's Heavy Cotton T-Shirt, Style G5000, Multipack",
      slug: "Gildan-Cotton-T-Shirt-2-Pack",
      image: "https://m.media-amazon.com/images/I/71kM3J7wfHL._AC_UX522_.jpg",
      price: 85,
      brand: "Gildan Store",
      rating: 4.1,
      numReviews: 200,
      countInStock: 210,
      description:
        "Solids: 100% Cotton; Sport Grey & antique Heather: 90% Cotton, 10% Polyester; Safety Colors & Heather: 50% Cotton, 50% Polyester",
    },
    {
      name: "Hanes Women's Short Sleeve V-Neck Graphic T-Shirt",
      slug: "Hanes-Graphic-multiple-graphics-available",
      image: "https://m.media-amazon.com/images/I/811n9roXHTL._AC_UY500_.jpg",
      price: 45,
      brand: "Hanes Store",
      rating: 4,
      numReviews: 100,
      countInStock: 12,
      description: "60% Polyester, 30% Cotton, 10% Rayon",
    },
    {
      name: "Black TShirt Men/Woman",
      slug: "black-tshirt-men-woman2",
      image: "https://m.media-amazon.com/images/I/714s29JGWIL._AC_UY500_.jpg",
      price: 12,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Tshit for men and women",
    },
    {
      name: "Gildan Men's Heavy Cotton T-Shirt, Style G5000, Multipack",
      slug: "Gildan-Cotton-T-Shirt-2-Pack2",
      image: "https://m.media-amazon.com/images/I/71kM3J7wfHL._AC_UX522_.jpg",
      price: 85,
      brand: "Gildan Store",
      rating: 4.1,
      numReviews: 200,
      countInStock: 210,
      description:
        "Solids: 100% Cotton; Sport Grey & antique Heather: 90% Cotton, 10% Polyester; Safety Colors & Heather: 50% Cotton, 50% Polyester",
    },
    {
      name: "Hanes Women's Short Sleeve V-Neck Graphic T-Shirt",
      slug: "Hanes-Graphic-multiple-graphics-available2",
      image: "https://m.media-amazon.com/images/I/811n9roXHTL._AC_UY500_.jpg",
      price: 45,
      brand: "Hanes Store",
      rating: 4,
      numReviews: 100,
      countInStock: 12,
      description: "60% Polyester, 30% Cotton, 10% Rayon",
    },
  ],
};
